### ISSUE TITLE
Plugin broken with Gradle 5.0-M1

### ISSUE THREAD

**Issue by eskatos** [ferranpons/twitter-gradle-plugin#14]
Fails with:
```
Caused by: java.lang.NoSuchMethodError: org.gradle.api.Project.property(Ljava/lang/Class;)Lorg/gradle/api/provider/PropertyState;Close stacktrace
```
https://scans.gradle.com/s/kcog2jburrieg/failure?openFailures=WzBd&openStackTraces=WzMse31d#top=0

That method has been deprecated for quite a while now. Should use `project.objects.property()` instead.

**Comment by ferranpons** [comment]
Hi @eskatos 

I'll check it and solve it ASAP. 

Many thanks for reporting it!

**Comment by ferranpons** [comment]
Hi @eskatos !

New version 1.1.0 available for download with the correction applied.

Please tell me if you still experience issues. Many thanks for your help!
